### ISSUE TITLE
Conversion between different units?

### ISSUE THREAD

**Issue by danielcroona** [scppc/paper-pricelist#1]
Hi!

Thanks a lot for this project and the thorough documentation. There is one thing that I am not able to understand though, regarding conversion between units.

If we have the unit RULLE and M for a product, where a RULLE consists of 50 x M, how is that supposed to be defined in the Price section of the XML data?

Do I use different Unit and ScaleUnit, like this?

```
<Price>
  <Amount>2251</Amount>
  <Unit>RULLE</Unit>
  <Factor>1000</Factor>
  <Scale>50</Scale>
  <ScaleUnit>M</ScaleUnit>
</Price>
```

**Comment by michael-bergman** [comment]
Hi and thank you for adopting the price-list standard!

_Scale_ and _ScaleUnit_ is only needed if you have discount prices. If not, set `<Scale>0</Scale>`.

I think it is a good idea to have the _SalesUnit_ set to M (Meter). This way you will be able to provide information about how many meters a packaging unit RULLE contains.

The pricing can preferably be “Kr per M”. Alternatively, you can also define it as “Kr per RULLE”. 

If packages are not allowed to be broken (i.e. only a whole RULLE is sold), you must define a _SalesMultiple_. You should also set `<Breakable>false</Breakable>`.

Example:

---
```
<Price>
  <Amount>2251</Amount>
  <Unit>M</Unit>
  <Factor>1000</Factor>
   ...
</Price>
```
The price is 2251.00 Kr per 1000 meters. 

---
```
<Price>
   ...
  <Scale>0</Scale>
  <ScaleUnit>M</ScaleUnit>
</Price>
```
The price is only applicable if you buy 0 meter or more.

---
```
<SalesUnit>M</SalesUnit>
<SalesMultiple>50</SalesMultiple>
<Breakable>false</Breakable>
```
You must buy in quantities of 50 meters.

---
```
<Packaging>
    <PackagingUnit>RULLE</PackagingUnit>
    <SalesUnitsPerPackagingUnit>50</SalesUnitsPerPackagingUnit>
</Packaging>
```
The article is packaged in a RULLE that contains 50 meters.

---

Hope this helped!

**Comment by danielcroona** [comment]
It helps a little bit. I might have read the specification wrong previously, because this makes me believe that there should be an ArticlePrice node fro every combination of an ArticleNumber and PackagingUnit, is that correct?

An example:
The article A12345-6 is available for purchase in the following Units:
- M
- RULLE - that consists of 100M
- PALL - that consists of 24RULLE

Should there be 3 different ArticlePrice nodes in the XML for this, or should all the different units be present within the same Price node? Your answer make me believe that the former is correct, but that will result in a lot of duplicated data in the XML file, right?

**Comment by michael-bergman** [comment]
There should be one _ArticlePrice_ element for each article having a unique article number.

For an _ArticlePrice_, there can be only one _SalesUnit_. However, multiple _Packaging_ are allowed.

In you example, the result of this may look like this:
```
<ArticlePrice>
  <ArticleNumber>A12345-6</ArticleNumber>
  <SalesUnit>M</SalesUnit>
  <Packaging>
    <PackagingUnit>RULLE</PackagingUnit>
    <SalesUnitsPerPackagingUnit>100</SalesUnitsPerPackagingUnit>
  </Packaging>
  <Packaging>
    <PackagingUnit>PALL</PackagingUnit>
    <SalesUnitsPerPackagingUnit>2400</SalesUnitsPerPackagingUnit>
  </Packaging>
</ArticlePrice>
```

**Comment by danielcroona** [comment]
OK, so that gives us the option to have multiple units under the Price-node, correct?

Something like this?
```
<ArticlePrice>
  <ArticleNumber>A12345-6</ArticleNumber>
  <SalesUnit>M</SalesUnit>
  <Packaging>
    <PackagingUnit>RULLE</PackagingUnit>
    <SalesUnitsPerPackagingUnit>100</SalesUnitsPerPackagingUnit>
  </Packaging>
  <Packaging>
    <PackagingUnit>PALL</PackagingUnit>
    <SalesUnitsPerPackagingUnit>2400</SalesUnitsPerPackagingUnit>
  </Packaging>
  <Price>
      <Amount>10</Amount>
      <Unit>M</Unit>
      <Factor>1</Factor>
      <Scale>0</Scale>
      <ScaleUnit>M</ScaleUnit>
    </Price>
  <Price>
      <Amount>9</Amount>
      <Unit>M</Unit>
      <Factor>1</Factor>
      <Scale>500</Scale>
      <ScaleUnit>M</ScaleUnit>
    </Price>
  <Price>
      <Amount>950</Amount>
      <Unit>RULLE</Unit>
      <Factor>1</Factor>
      <Scale>0</Scale>
      <ScaleUnit>RULLE</ScaleUnit>
    </Price>
    <Price>
      <Amount>21950</Amount>
      <Unit>PALL</Unit>
      <Factor>1</Factor>
      <Scale>0</Scale>
      <ScaleUnit>PALL</ScaleUnit>
    </Price>
</ArticlePrice>
```

**Comment by michael-bergman** [comment]
If you decide to have multiple _Price_ elements this should be in the case that you want to describe discounted prices / graduated prices.

Unfortunately, there is a limited amount of restrictions and validations within the standard. This means that the standard does not permit you from mixing units in each level.

You might want to check with the recipient of your file if they have any additional requirements in order to ensure a successful parsing.

**Comment by danielcroona** [comment]
OK, thanks, we'll go with my example above and then let our partners try it out.

Thank you very much for your help.
